apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: portfolio_front
  newName: salamanteri/portfolio_front
  newTag: dd5a3a4d766e5d3f83138cae60d6e9b1723b0da1
- name: portfolio_page
  newName: portfolio_page
  newTag: v1
