apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: portfolio_page
  newName: salamanteri/portfolio_page
  newTag: 5aeaf44437306029379cba90e06d9718a3952679
