apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: salamanteri/aks-nodejs-argocd
  newTag: 23185ebc7bad96ee8c546a49749a983dedb17621
