apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: portfolio_front
  newName: salamanteri/portfolio_front
  newTag: 1c65244602b4d8dc884f430f073a2caeecde1110
- name: portfolio_page
  newName: portfolio_page
  newTag: v1
