apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-nodejs-argocd
  newName: salamanteri/aks-nodejs-argocd
  newTag: 09723163b6b5b285edc7feffc816aa15cdecfbbe
