apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: nodejs
  name: nodejs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: nodejs
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: nodejs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - image: portfolio_page:v1
        name: portfolio_page
        ports:
        - containerPort: 3000
          name: http
      nodeSelector:
        beta.kubernetes.io/os: linux
