name: Docker

on:
  pull_request:
    branches:
      - main

env:
    IMAGE_NAME: portfolio-docker

jobs:
    build:
        name: Build a container image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name:
              id: tag
              uses: dawidd6/action-get-tag@v1
            - name: Log into registry
              uses: docker/login-action@v1
              with:
                registry: ${{ secrets.ACR_ENDPOINT }}
                username: ${{ secrets.ACR_USERNAME }}
                password: ${{ secrets.ACR_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                push: true
                build-args: |
                    version=${{ steps.tag.outputs.tag }}
                tags: ${{ secrets.ACR_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ steps.tag.outputs.tag }}