name: Docker

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGINSERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        run: |
          docker build . -t ${{ secrets.ACR_LOGINSERVER }}/portfolio-docker:latest
          docker push ${{ secrets.ACR_LOGINSERVER }}/portfolio-docker:latest
